Repository exoego/scala-js-ts-importer, pull requests merged in 2020-07, with the labels that each got.

#117 Generate psuedo enum for type aliases of literal
  importer/src/main/scala/org/scalajs/tools/tsimporter/Config.scala
  importer/src/main/scala/org/scalajs/tools/tsimporter/Importer.scala
  importer/src/main/scala/org/scalajs/tools/tsimporter/Kicker.scala
  importer/src/main/scala/org/scalajs/tools/tsimporter/Trees.scala
  importer/src/main/scala/org/scalajs/tools/tsimporter/sc/Definitions.scala
  importer/src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala
  importer/src/test/scala/org/scalajs/tools/tsimporter/ImporterConfigSpec.scala
  importer/src/test/scala/org/scalajs/tools/tsimporter/ImporterSpec.scala
  index.html
  samples/config/type-alias-enum/generate.scala
  samples/config/type-alias-enum/source.d.ts
  webapp/src/main/resources/webapp-opt.js
  webapp/src/main/scala/org/scalajs/tools/tsimporter/WebAppMain.scala
Labels: enhancement

#119 Empty tuple should be empty array of nothing, so no element can be added
  importer/src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
  samples/array.d.ts
  samples/array.d.ts.scala
  webapp/src/main/resources/webapp-opt.js
Labels: enhancement

#121 Ignore import with require
  importer/src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
  samples/import.d.ts
  webapp/src/main/resources/webapp-opt.js
Labels: bug

#123 Ignore export object literal
  importer/src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala
  samples/export.d.ts
  samples/export.d.ts.scala
  webapp/src/main/resources/webapp-opt.js
Labels: bug

#125 Update scala-js-nodejs-v12 to 0.12.0
  build.sbt
Labels: chore
